Models/Board.cs
namespace DashboardAgro.Models
{
    public class Board
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual Location Location { get; set; }
    }
}

Controllers/BoardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DashboardAgro.Models;
using Newtonsoft.Json;
using System.Threading;

namespace DashboardAgro.Controllers
{
    public class BoardsController : Controller
    {
        private readonly DashContext _context;

        public BoardsController(DashContext context)
        {
            _context = context;
        }

        // GET: Boards
        public async Task<IActionResult> Index()
        {
            Thread.Sleep(500);
            return View(await _context.Boards.ToListAsync());
        }

        public IActionResult DisplayUserList()
        {
            return View(_context.Users.ToList());
        }

        // GET: Boards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var board = await _context.Boards
                .Include(c => c.Location)
                    .ThenInclude(c => c.MapPoints)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (board == null)
            {
                return NotFound();
            }

            return View(board);
        }

        // GET: Boards/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Boards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Location")] Board board)
        {
            if (ModelState.IsValid)
            {
                _context.Add(board);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(board);
        }

        // GET: Boards/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var board = await _context.Boards.FindAsync(id);
            if (board == null)
            {
                return NotFound();
            }
            return View(board);
        }

        // POST: Boards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Location")] Board board)
        {
            if (id != board.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(board);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoardExists(board.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(board);
        }

        // GET: Boards/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var board = await _context.Boards
                .FirstOrDefaultAsync(m => m.Id == id);
            if (board == null)
            {
                return NotFound();
            }

            return View(board);
        }

        // POST: Boards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var board = await _context.Boards.FindAsync(id);
            _context.Boards.Remove(board);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> SaveLocation(string name, string locations)
        {
            var points = JsonConvert.DeserializeObject<List<List<MapPointDTO>>>(locations);
            var innerPoints = points.FirstOrDefault();

            var mapPoints = innerPoints.Select(c => new MapPoint()
            {
                Name = name,
                Altitude = c.Altitude,
                Latitude = c.Latitude,
                Longitude = c.Longitude,
                AltitudeReference = c.AltitudeReference
            });

            var location = new Location()
            {
                MapPoints = mapPoints.ToList()
            };

            var board = new Board()
            {
                Name = name,
                Location= location
            };

            await _context.AddAsync(board);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool BoardExists(int id)
        {
            return _context.Boards.Any(e => e.Id == id);
        }
    }
}

public class MapPointDTO
{
    public int AltitudeReference { get; set; }
    public int Altitude { get; set; }
    public decimal Longitude { get; set; }
    public decimal Latitude { get; set; }
}

Views/Boards/Create.cshtml
@model DashboardAgro.Models.Board

@{
    ViewData["Title"] = "Create";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/create.css" />
    <script type='text/javascript'
            src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap'
            async defer></script>

    <script src="~/js/map4.js"></script>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="Create your own fully custom drawing toolbar and controls." />
    <meta name="keywords" content="Microsoft maps, map, gis, API, SDK, Bing, Bing Maps" />
    <meta name="author" content="Microsoft Bing Maps" />
    <meta name="screenshot" content="screenshot.jpg" />
</head>

<body>
    <br />
    <h1>Create a new land</h1>
    <hr />
    <input type="button" class="btn btn-primary" value="Get Location" onclick="getShapes()" />
    <div id='searchBoxContainer' class="mt-3">
        <input placeholder="Search location..." class="form-control w-25 h-75" type='text' id='searchBox' />
        <input class="btn btn-primary mt-1" type='button' value='Search' onclick='geocode()' />
    </div>

    <br />
    <br />
    <div class="grid-container">
        
        <div class="grid-item" id="first">
            <div id="myMap" style="position:relative;width:600px;height:400px;"></div>
        </div>
        <div class="grid-item" id="second">
            <div class="row">
                <div class="col-md-4 ">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input id="name" asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Location" class="control-label" id="location"></label>
                            <span asp-validation-for="Location" class="text-danger"></span>
                        </div>
                        <br />

                    <div id="output"></div>
                <form asp-controller="Boards" asp-action="Index">

                        <div class="form-group">
                            <button onclick="SaveLocation()" type="submit" class="btn btn-primary">Create</button>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>



    <div>
        <a class="btn btn-primary" asp-action="Index">Back to List</a>
    </div>
</body>




@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
</html>

Views/Boards/Delete.cshtml
@model DashboardAgro.Models.Board

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Board</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
       
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Boards/Details.cshtml
@using Newtonsoft.Json;
@model DashboardAgro.Models.Board

@{
    ViewData["Title"] = "Details";
}

@*<script src="~/js/detail.js"></script>*@
<script type='text/javascript'
        src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap'
        async defer></script>
<link rel="stylesheet" href="~/css/detail.css" />
@{
    var mapPoints = Model.Location.MapPoints.Select(c => new { c.Latitude, c.Longitude}).ToList();
}

<h1>Details</h1>
<body>
    <div class="grid-container">
        <div class="row">
            <div id="myMap" style="position:relative;width:600px;height:400px;"></div>
        </div>

        @*Weather table*@
        <div class="row">
            <table id="table" class="table table-striped ">
                <thead class="thead-dark">
                    <tr>
                       
                        <th scope="col">Forecast</th>
                        <th scope="col">Temperature</th>
                        <th scope="col">Humidity</th>
                        <th scope="col">Pressure</th>
                    </tr>
                </thead>
                <tbody id="table_body">
                    <tr>
                        
                        <td>hello</td>
                        <td>hello</td>
                        <td>hello</td>
                        <td>hello</td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>


</body>

<div>
    <a class="btn btn-info" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    <a class="btn btn-danger" asp-action="Index">Back to List</a>
</div>
@{
    var myLocations = JsonConvert.SerializeObject(mapPoints, Formatting.None,
                        new JsonSerializerSettings()
                                {
                                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                                });
}
<script>
    var longitude = parseFloat("@mapPoints.FirstOrDefault().Longitude.ToString();")
    var latitude = parseFloat("@mapPoints.FirstOrDefault().Latitude.ToString();")
    

    let fetchLink = 'https://api.agromonitoring.com/agro/1.0/weather?lat=' + latitude +
        '&lon=' + longitude + '&appid=f39712e654bf3acf782c64b78437f540';
    

    fetch(fetchLink)
        .then((data) => {
            return data.json();
        }).then((completeData) => {
            console.log(completeData.weather);
            console.log(completeData.main);
            console.log(completeData.main.humidity);

            let tableData = "";

            let valNum = parseFloat(completeData.main.temp);
            let temp = (valNum - 273.15).toFixed(1);

            completeData.weather.map((values) => {
                tableData =
                    `<tr>
                
                <td>${values.description}</td>
                <td>${temp}°C</td>
                <td>${completeData.main.humidity}%</td>
                <td>${completeData.main.pressure} mmHg</td>
                </tr>`;
            });

            document.getElementById('table_body').innerHTML = tableData;
        })

    function GetMap() {
        map = new Microsoft.Maps.Map('#myMap', {
            credentials: 'Aq1cH-6S5LPVeMtUB5ptNesziKfdnk0W6j6pZ5zpSWKYM9BgYTFBDSDvMu68T9Lh',

            mapTypeId: Microsoft.Maps.MapTypeId.aerial,
            zoom: 10
        });

        //Request the user's location
        navigator.geolocation.getCurrentPosition(function (position) {
            var latitude = parseFloat("@mapPoints.FirstOrDefault().Latitude");
            var longitude = parseFloat("@mapPoints.FirstOrDefault().Longitude");
            var loc = new Microsoft.Maps.Location(
                latitude,
                longitude);

            //Add a pushpin at the user's location.
            var pushpin = new Microsoft.Maps.Pushpin(loc, {
                icon: 'https://www.bingmapsportal.com/Content/images/poi_custom.png',
                title: 'Selected location',
            });

            var actualLocations = @Html.Raw(myLocations);
            
            let microsoftPoints = [];

            actualLocations.forEach((element, index, array) => {
                console.log(element);
                microsoftPoints.push(new Microsoft.Maps.Location(element.Latitude, element.Longitude))
            });

            var polygon = new Microsoft.Maps.Polygon(microsoftPoints);


            map.entities.push(polygon);
            map.entities.push(pushpin);
            map.setView({ center: loc, zoom: 15 });
        });
    }

</script>

Views/Boards/DisplayUserList.cshtml
@{
    ViewData["Title"] = "DisplayUserList";
}

<h1>User List</h1>

<p>
    <a asp-action="DisplayUserList" asp-controller="Boards">

    </a>
    <table>

        <thead>
            <tr>
                <th width="400px">
                    Id
                </th>

                <th width="300px">
                    Email
                </th>
                <th></th>
            </tr>
        </thead>
        @foreach (var users in Model)
        {
            <tr>
                <td width="300px">
                    @users.Id
                </td>

                <td width="300px">
                    @users.Email
                </td>

            </tr>
        }
    </table>
</p>

Views/Boards/Edit.cshtml
@model DashboardAgro.Models.Board

@{
    ViewData["Title"] = "Edit";
}
<style>
    body {
        background-color: #e8f0c0;
    }
</style>

<h1>Edit</h1>

<h4>Board</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Boards/Index.cshtml
@model IEnumerable<DashboardAgro.Models.Board>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="~/css/index.css" />
<style>
    body {
        background-color: #e8f0c0;
    }
</style>

<h1>Land Board</h1>
<br />
<p>
    <a class="btn btn-success btn-lg" asp-action="Create">Create New</a>
</p>



<div class="grid-container">


    @foreach (var item in Model)
    {

        <div>
            @Html.DisplayFor(modelItem => item.Name)
            <br />

            @*@Html.DisplayFor(modelItem => item.Location)*@
            <br />

            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
            <a class="btn btn-outline-dark" asp-action="Details" asp-route-id="@item.Id">Details</a>
            <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>

        </div>
    }
</div>

<style>
    .grid-container {
        display: grid;
        grid-template-columns: auto auto auto auto;
        gap: 10px;
        padding: 10px;
    }

        .grid-container > div {
            background: rgba(255, 255, 255, 0.41);
            border-radius: 16px;
            box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
            backdrop-filter: blur(5px);
            -webkit-backdrop-filter: blur(5px);
            text-align: center;
            padding: 20px 0;
            font-size: 30px;
        }
</style>